### ISSUE TITLE
Clojure 1.9 is released :-)

### ISSUE THREAD

**Issue by marco-m** [Engelberg/rolling-stones#1]
Hello, README says:

> Rolling Stones currently requires Clojure 1.9 alpha 14 or higher due to a dependency on the new spec library. This library will remain in alpha as long as Clojure 1.9 is in alpha. I will put out an official, non-snapshot release of this library when Clojure 1.9 is released.

:-)

**Comment by Engelberg** [comment]
Unfortunately spec has remained in alpha, which is why I haven't released a
non-snapshot version.

**Comment by marco-m** [comment]
Ah yes, sure! I am closing this one, sorry for the noise.

**Comment by Engelberg** [comment]
Would a point release be helpful for your use of the library? I don't want
to stop people from using it.

**Comment by marco-m** [comment]
Thanks for the kind offer Mark; using the SNAPSHOT is fine for me, I just saw the text in the README and I though you might have forgotten, while I was forgetting the particular history of Clojure 1.9 and spec alpha :-D
